#:kivy 2.3.0

<ClipboardLayout>:
    orientation: 'vertical'
    Label:
        id: history_label
        text: '剪贴板历史记录将在此显示'
        font_name: 'NotoSans'
        size_hint_y: None
        height: self.texture_size[1]
        text_size: self.width, None
        halign: 'left'
        valign: 'top'
    Button:
        text: '查看剪贴板历史记录'
        font_name: 'NotoSans'
        size_hint_y: 0.1
        on_press: root.show_clipboard_history()
